export const CONSTANTS = Object.freeze({
  BASE_SCORE: 0,
  MAX_SCORE: 100,
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  BASE_SCORE: 30,
  MARK_CAP: 100,
  ATTENDANCE_FULL: 2.5,
  ATTENDANCE_HALF: 1.0,
  ATTENDANCE_MISSED: -5.0,
  QUIZ_MISSED: -2.5,
  QUIZ_MAX: 5,
  ASSIGNMENT_MAX: 10,
  LATE_ASSIGNMENT_SCORE: 0,
  JWT_ACCESS_EXPIRY: '15m',
  JWT_REFRESH_EXPIRY: '7d',
  REVIEW_RETRY_DELAYS: [60000, 300000, 900000],  // 1min, 5min, 15min
  METRIC_CACHE_TTL: 300,  // seconds
  MAX_NOTES_PER_TOPIC: 5,
  MAX_NOTE_SIZE_MB: 10,
  MIN_OVERRIDE_REASON_LENGTH: 20,
});